<?php

// PARA RESETAR E REPOVOAR O BANCO INTEIRO: php artisan migrate:fresh --seed
// PARA RODAR UMA LISTA ESPECIFICA SEM DROPAR O BANCO:
//   php artisan db:seed --class="Database\Seeders\Lists\PortableBlendersSeeder"

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents; // DESATIVA EVENTOS DE MODEL DURANTE O SEED
use Illuminate\Database\Seeder; // IMPORTA A CLASSE BASE DOS SEEDERS

class DatabaseSeeder extends Seeder
{
    use WithoutModelEvents; // EVITA DISPARAR OBSERVERS/EVENTOS DURANTE O SEED

    public function run(): void // APENAS REGISTRA OS SEEDERS DE LISTA (SEM DADOS HARDCODED)
    {
        $this->call([ // CHAMA CADA SEEDER DE LISTA EM ORDEM
            \Database\Seeders\Lists\PortableBlendersSeeder::class, // LISTA DE LIQUIDIFICADORES PORTATEIS (KITCHEN)
            \Database\Seeders\Lists\PortableFansSeeder::class, // LISTA DE VENTILADORES PORTATEIS (HOME)
            \Database\Seeders\Lists\WorkoutTankTopsSeeder::class, // LISTA DE REGATAS DE TREINO FEMININAS (FITNESS)
            \Database\Seeders\Lists\AndroidPhonesSeeder::class, // LISTA DE SMARTPHONES ANDROID (TECH)
            \Database\Seeders\Lists\SpinMopsSeeder::class, // LISTA DE SPIN MOPS (HOME)
            \Database\Seeders\Lists\MicroSDCardsSeeder::class, // LISTA DE CARTOES MICROSD 256GB (TECH)
            \Database\Seeders\Lists\PcSpeakersSeeder::class, // LISTA DE CAIXAS DE SOM PARA PC (HOME & OFFICE)
            \Database\Seeders\Lists\RetractableGardenHoseSeeder::class, // LISTA DE MANGUEIRAS RETRATEIS DE JARDIM (GARDEN)
            \Database\Seeders\Lists\CatToysSeeder::class, // LISTA DE BRINQUEDOS PARA GATOS (PET SUPPLIES)
            \Database\Seeders\Lists\SolarPoolIonizerSeeder::class, // LISTA DE IONIZADORES SOLARES PARA PISCINA (GARDEN)
            \Database\Seeders\Lists\Smart4kProjectorSeeder::class, // LISTA DE PROJETORES SMART 4K (TECH)
            \Database\Seeders\Lists\GamingMonitors27Seeder::class, // LISTA DE MONITORES GAMER DE 27 POLEGADAS (TECH)
            \Database\Seeders\Lists\GamingKeyboardsSeeder::class, // LISTA DE TECLADOS GAMER (TECH)
            \Database\Seeders\Lists\MicroSD128Seeder::class, // LISTA DE CARTOES MICROSD 128GB (TECH)
            \Database\Seeders\Lists\MicroSD64Seeder::class, // LISTA DE CARTOES MICROSD 64GB (TECH)
            \Database\Seeders\Lists\PS5SsdSeeder::class, // LISTA DE SSDs NVMe 2TB PARA PS5 (TECH)
            \Database\Seeders\Lists\DehumidifiersSeeder::class, // LISTA DE DESUMIDIFICADORES (HOME)
            \Database\Seeders\Lists\HeatedClothesAirersSeeder::class, // LISTA DE VARAIS AQUECIDOS (HOME)
            \Database\Seeders\Lists\CordlessLeafBlowersSeeder::class, // LISTA DE SOPRADORES DE FOLHAS A BATERIA (GARDEN)
            \Database\Seeders\Lists\SelfCleaningLitterBoxesSeeder::class, // LISTA DE CAIXAS DE AREIA AUTOLIMPANTES (PET SUPPLIES)
            \Database\Seeders\Lists\StandingDesksSeeder::class, // LISTA DE MESAS DE ALTURA REGULAVEL (HOME & OFFICE)
            \Database\Seeders\Lists\GamingMiceSeeder::class, // LISTA DE MOUSES GAMER (TECH)
            \Database\Seeders\Lists\ElectricBlanketsSeeder::class, // LISTA DE COBERTORES ELETRICOS (HOME)
            \Database\Seeders\Lists\AdjustableDumbbellsSeeder::class, // LISTA DE HALTERES AJUSTAVEIS (FITNESS)
            \Database\Seeders\Lists\AutomaticCatFeedersSeeder::class, // LISTA DE ALIMENTADORES AUTOMATICOS (PET SUPPLIES)
            \Database\Seeders\Lists\PaperShreddersSeeder::class, // LISTA DE FRAGMENTADORAS DE PAPEL (HOME & OFFICE)
            \Database\Seeders\Lists\WaterFilterJugsSeeder::class, // LISTA DE JARRAS COM FILTRO (KITCHEN)
            \Database\Seeders\Lists\MassageGunsSeeder::class, // LISTA DE PISTOLAS DE MASSAGEM (FITNESS)
            \Database\Seeders\Lists\OilFilledRadiatorsSeeder::class, // LISTA DE RADIADORES A OLEO (HOME)
            \Database\Seeders\Lists\VacuumSealersSeeder::class, // LISTA DE SELADORAS A VACUO (KITCHEN)
            \Database\Seeders\Lists\PowerBanksSeeder::class, // LISTA DE POWER BANKS (TECH)
            \Database\Seeders\Lists\HumidifiersSeeder::class, // LISTA DE UMIDIFICADORES (HOME)
            \Database\Seeders\Lists\FoodDehydratorsSeeder::class, // LISTA DE DESIDRATADORES DE ALIMENTOS (KITCHEN)
            \Database\Seeders\Lists\MonitorArmsSeeder::class, // LISTA DE BRACOS DE MONITOR (HOME & OFFICE)
            \Database\Seeders\Lists\DashCamsSeeder::class, // LISTA DE DASH CAMS (TECH)
            \Database\Seeders\Lists\SousVideCookersSeeder::class, // LISTA DE CIRCULADORES SOUS VIDE (KITCHEN)
            \Database\Seeders\Lists\CatWaterFountainsSeeder::class, // LISTA DE FONTES DE AGUA PARA GATO (PET SUPPLIES)
            \Database\Seeders\Lists\PressureWashersSeeder::class, // LISTA DE LAVADORAS DE ALTA PRESSAO (GARDEN)
            \Database\Seeders\Lists\SmartScalesSeeder::class, // LISTA DE BALANCAS INTELIGENTES (FITNESS)
            \Database\Seeders\Lists\SteamMopsSeeder::class, // LISTA DE MOPS A VAPOR (HOME)
            \Database\Seeders\Lists\CoffeeGrindersSeeder::class, // LISTA DE MOEDORES DE CAFE (KITCHEN)
            \Database\Seeders\Lists\DeskLampsSeeder::class, // LISTA DE LUMINARIAS DE MESA (HOME & OFFICE)
            \Database\Seeders\Lists\WindowVacuumsSeeder::class, // LISTA DE ASPIRADORES DE JANELA (HOME)
            \Database\Seeders\Lists\SlowCookersSeeder::class, // LISTA DE SLOW COOKERS (KITCHEN)
            \Database\Seeders\Lists\SoupMakersSeeder::class, // LISTA DE SOUP MAKERS (KITCHEN)
            \Database\Seeders\Lists\BreadMakersSeeder::class, // LISTA DE MAQUINAS DE PAO (KITCHEN)
            \Database\Seeders\Lists\AirPurifiersSeeder::class, // LISTA DE PURIFICADORES DE AR (HOME)
            \Database\Seeders\Lists\WalkingPadsSeeder::class, // LISTA DE WALKING PADS / ESTEIRAS DE MESA (FITNESS)
            \Database\Seeders\Lists\LaptopStandsSeeder::class, // LISTA DE SUPORTES DE NOTEBOOK (HOME & OFFICE)
            \Database\Seeders\Lists\SteamGeneratorIronsSeeder::class, // LISTA DE CENTRAIS DE VAPOR (HOME)
            \Database\Seeders\Lists\RiceCookersSeeder::class, // LISTA DE PANELAS DE ARROZ (KITCHEN)
            \Database\Seeders\Lists\FanHeatersSeeder::class, // LISTA DE AQUECEDORES A VENTILACAO (HOME)
            \Database\Seeders\Lists\IndoorSecurityCamerasSeeder::class, // LISTA DE CAMERAS DE SEGURANCA INTERNAS (TECH)
            \Database\Seeders\Lists\PortableMonitorsSeeder::class, // LISTA DE MONITORES PORTATEIS (HOME & OFFICE)
            \Database\Seeders\Lists\ExerciseBikesSeeder::class, // LISTA DE BIKES ERGOMETRICAS (FITNESS)
            \Database\Seeders\Lists\DogClippersSeeder::class, // LISTA DE MAQUINAS DE TOSA (PET SUPPLIES)
            \Database\Seeders\Lists\WebcamsSeeder::class, // LISTA DE WEBCAMS (HOME & OFFICE)
            \Database\Seeders\Lists\ResistanceBandsSeeder::class, // LISTA DE FAIXAS ELASTICAS (FITNESS)
            \Database\Seeders\Lists\PetHairVacuumsSeeder::class, // LISTA DE ASPIRADORES PARA PELO DE PET (PET SUPPLIES)
            \Database\Seeders\Lists\PortableSsdsSeeder::class, // LISTA DE SSDs PORTATEIS (TECH)
            \Database\Seeders\Lists\SolarSecurityLightsSeeder::class, // LISTA DE LUZES DE SEGURANCA SOLARES (GARDEN)
            \Database\Seeders\Lists\GardenStorageBoxesSeeder::class, // LISTA DE BAUS DE JARDIM (GARDEN)
            \Database\Seeders\Lists\SadLampsSeeder::class, // LISTA DE LUMINARIAS DE FOTOTERAPIA SAD (HOME)
            \Database\Seeders\Lists\EspressoMachinesSeeder::class, // LISTA DE MAQUINAS DE ESPRESSO (KITCHEN)
            \Database\Seeders\Lists\CarpetCleanersSeeder::class, // LISTA DE LAVADORAS DE CARPETE (HOME)
            \Database\Seeders\Lists\TemperatureControlKettlesSeeder::class, // LISTA DE CHALEIRAS COM CONTROLE DE TEMPERATURA (KITCHEN)
            \Database\Seeders\Lists\UsbCDockingStationsSeeder::class, // LISTA DE DOCKING STATIONS USB-C (HOME & OFFICE)
            \Database\Seeders\Lists\SmartPlugsSeeder::class, // LISTA DE TOMADAS INTELIGENTES (TECH)
            \Database\Seeders\Lists\StandMixersSeeder::class, // LISTA DE BATEDEIRAS PLANETARIAS (KITCHEN)
            \Database\Seeders\Lists\VibrationPlatesSeeder::class, // LISTA DE PLATAFORMAS VIBRATORIAS (FITNESS)
            \Database\Seeders\Lists\MonitorLightBarsSeeder::class, // LISTA DE BARRAS DE LUZ DE MONITOR (HOME & OFFICE)
            \Database\Seeders\Lists\MultiPortChargersSeeder::class, // LISTA DE CARREGADORES USB-C MULTI-PORTA (TECH)
            \Database\Seeders\Lists\GpsPetTrackersSeeder::class, // LISTA DE RASTREADORES GPS PARA PETS (PET SUPPLIES)
            \Database\Seeders\Lists\SmartRadiatorValvesSeeder::class, // LISTA DE VALVULAS TERMOSTATICAS INTELIGENTES (HOME)
            \Database\Seeders\Lists\CordlessVacuumsSeeder::class, // LISTA DE ASPIRADORES VERTICAIS SEM FIO (HOME)
            \Database\Seeders\Lists\MiniChainsawsSeeder::class, // LISTA DE MINI MOTOSSERRAS SEM FIO (GARDEN)
            \Database\Seeders\Lists\MicrowavesSeeder::class, // LISTA DE MICRO-ONDAS (KITCHEN)
            \Database\Seeders\Lists\PetCamerasSeeder::class, // LISTA DE CAMERAS PARA PETS (PET SUPPLIES)
            \Database\Seeders\Lists\SmartThermostatsSeeder::class, // LISTA DE TERMOSTATOS INTELIGENTES (HOME)
            \Database\Seeders\Lists\WeightedBlanketsSeeder::class, // LISTA DE COBERTORES PESADOS (HOME)
            \Database\Seeders\Lists\KitchenScalesSeeder::class, // LISTA DE BALANCAS DE COZINHA (KITCHEN)
            \Database\Seeders\Lists\MultiCookersSeeder::class, // LISTA DE MULTICOOKERS / PANELAS DE PRESSAO (KITCHEN)
            \Database\Seeders\Lists\VideoDoorbellsSeeder::class, // LISTA DE VIDEO CAMPAINHAS (TECH)
            \Database\Seeders\Lists\PortablePowerStationsSeeder::class, // LISTA DE ESTACOES DE ENERGIA PORTATEIS (TECH)
            \Database\Seeders\Lists\FootSpasSeeder::class, // LISTA DE ESCALDA-PES / FOOT SPAS (HOME)
            \Database\Seeders\Lists\WeatherStationsSeeder::class, // LISTA DE ESTACOES METEOROLOGICAS (GARDEN)
            \Database\Seeders\Lists\HandWarmersSeeder::class, // LISTA DE AQUECEDORES DE MAO RECARREGAVEIS (HOME)
            \Database\Seeders\Lists\ToastersSeeder::class, // LISTA DE TORRADEIRAS (KITCHEN)
            \Database\Seeders\Lists\WinterDuvetsSeeder::class, // LISTA DE EDREDONS DE INVERNO POR TOG (HOME)
            \Database\Seeders\Lists\SoundbarsSeeder::class, // LISTA DE SOUNDBARS PARA TV (TECH)
            \Database\Seeders\Lists\JumpStartersSeeder::class, // LISTA DE ARRANCADORES DE BATERIA (TECH)
            \Database\Seeders\Lists\TyreInflatorsSeeder::class, // LISTA DE CALIBRADORES DE PNEU (TECH)
            \Database\Seeders\Lists\HandMixersSeeder::class, // LISTA DE BATEDEIRAS DE MAO (KITCHEN)
            \Database\Seeders\Lists\ToastieMakersSeeder::class, // LISTA DE SANDUICHEIRAS (KITCHEN)
            \Database\Seeders\Lists\CatTreesSeeder::class, // LISTA DE ARRANHADORES/TORRES PARA GATOS (PET SUPPLIES)
            \Database\Seeders\Lists\GarmentSteamersSeeder::class, // LISTA DE VAPORIZADORES DE ROUPA (HOME)
            \Database\Seeders\Lists\SmokeCoAlarmsSeeder::class, // LISTA DE ALARMES DE FUMACA E MONOXIDO (HOME)
            \Database\Seeders\Lists\YogaMatsSeeder::class, // LISTA DE TAPETES DE YOGA (FITNESS)
            \Database\Seeders\Lists\GardenShreddersSeeder::class, // LISTA DE TRITURADORES DE JARDIM (GARDEN)
            // ADICIONE NOVAS LISTAS AQUI, UMA POR LINHA, CONFORME FOREM CRIADAS
        ]);
    }
}
