<?php

namespace App\Http\Middleware; // NAMESPACE DOS MIDDLEWARES DA APLICACAO

use Closure; // TIPO DO PROXIMO PASSO DA PILHA DE MIDDLEWARE
use Illuminate\Http\Request; // REQUISICAO HTTP
use Symfony\Component\HttpFoundation\Response; // RESPOSTA HTTP

class CachePublicPages
{
    // O SITE E 100% LEITURA: SO ROTAS GET, NENHUM POST, NENHUM @csrf E NENHUM USO DE SESSAO NAS VIEWS.
    // MESMO ASSIM O LARAVEL DEVOLVIA "Cache-Control: no-cache, private" EM TODA PAGINA, O QUE PROIBIA
    // A CLOUDFLARE DE GUARDAR O HTML NA BORDA (cf-cache-status: DYNAMIC) E JOGAVA TODO ACESSO NO ORIGIN.
    // ESTE MIDDLEWARE TROCA ESSE CABECALHO NAS PAGINAS PUBLICAS.
    public function handle(Request $request, Closure $next): Response
    {
        $response = $next($request); // DEIXA A REQUISICAO SEGUIR E PEGA A RESPOSTA PRONTA

        if (! $request->isMethodCacheable() || $response->getStatusCode() !== 200) { // SO GET/HEAD QUE DERAM 200
            return $response; // QUALQUER OUTRA COISA (404, REDIRECT, POST FUTURO) SAI SEM CACHE PUBLICO
        }

        // s-maxage MANDA NO CACHE COMPARTILHADO (CLOUDFLARE): 2 HORAS NA BORDA.
        // max-age=0 MANDA NO NAVEGADOR: ELE SEMPRE REVALIDA, PORQUE CACHE DE NAVEGADOR NAO TEM BOTAO DE PURGE
        // E UM RE-SEED FICARIA PRESO NA MAQUINA DO VISITANTE. A BORDA A GENTE LIMPA COM UM CLIQUE.
        // stale-while-revalidate DEIXA A CLOUDFLARE SERVIR O CONTEUDO VENCIDO POR ATE 24H ENQUANTO BUSCA
        // O NOVO EM SEGUNDO PLANO, ENTAO A EXPIRACAO NUNCA APARECE COMO LENTIDAO PARA O VISITANTE.
        $response->headers->set('Cache-Control', 'public, max-age=0, s-maxage=7200, stale-while-revalidate=86400');

        // A CLOUDFLARE SE RECUSA A GUARDAR QUALQUER RESPOSTA QUE TENHA Set-Cookie, E O LARAVEL CARIMBA
        // laravel-session E XSRF-TOKEN EM TODA PAGINA MESMO SEM NINGUEM USAR SESSAO. SEM REMOVER ESSES
        // DOIS COOKIES O CABECALHO ACIMA NAO ADIANTA NADA — A BORDA CONTINUA DEVOLVENDO DYNAMIC.
        // ⚠️ SE ALGUM DIA ENTRAR UM FORMULARIO (CONTATO, NEWSLETTER COM @csrf), A PAGINA QUE O EXIBE
        // PRECISA SER EXCLUIDA AQUI, SENAO O TOKEN CSRF NAO CHEGA NO NAVEGADOR E O ENVIO FALHA.
        $response->headers->remove('Set-Cookie'); // TIRA OS COOKIES DE SESSAO DAS PAGINAS PUBLICAS
        $response->headers->remove('Vary');       // SEM COOKIE NAO HA POR QUE VARIAR A RESPOSTA POR ELE

        return $response; // DEVOLVE A RESPOSTA CACHEAVEL E SEM COOKIE
    }
}
